---
- hosts: all
  become: yes
  gather_facts: yes 
  tasks:
  - name: I want to install apache2 webserver on ubuntu node
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"

  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted
