---
- hosts: all
  become: yes
  tasks:
  - name: I want to install apache2 webserver on ubuntu node
    apt:
      name: apache2
      state: present

  - name: I want to start apache2 webserver in the node machine
    service:
      name: apache2
      state: systemctl start
